<a href="https://colab.research.google.com/github/zaidcontractor/ds1002-kna6rp/blob/main/Copy_of_week_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework - Week 5

Complete the following blocks as specified in the directions. Run each cell to return the desired output. Save your notebook back to your GitHub repository and submit the GitHub URL for your notebook for review.

## 1. NumPy

You have three Python lists (below). Put them into a single NumPy `ndarray` as a 2-dimensional array (with 6 columns and 3 rows). Using the 6 columns in each list, add each column's values and print out the added values. Demonstrate everything required to code such an operation in the code block below.

```python
val1 = [12,14,16,18,20,22]
val2 = [5,10,15,20,25,30]
val3 = [5,7,9,11,13,15]
```

In [2]:
# Set up numpy and create an array from the 3 lists above. Don't just copy and
# paste the values into a new array by hand, use the three variables to create it.
import numpy as np

val1 = [12,14,16,18,20,22]
val2 = [5,10,15,20,25,30]
val3 = [5,7,9,11,13,15]

my_array = np.array([val1, val2, val3])
print(my_array)

#column 1
column_one = my_array[:,0]
print(column_one)

total = 0
for i in range (0,column_one.size):
  total += column_one[i]

print("The sum of column 1's values is: " + str(total))

#column 2
column_two = my_array[:,1]
print(column_two)

total = 0
for i in range (0,column_two.size):
  total += column_two[i]

print("The sum of column 2's values is: " + str(total))

#column 3
column_three = my_array[:,2]
print(column_three)

total = 0
for i in range (0,column_three.size):
  total += column_three[i]

print("The sum of column 3's values is: " + str(total))

#column 4
column_four = my_array[:,3]
print(column_four)

total = 0
for i in range (0,column_four.size):
  total += column_four[i]

print("The sum of column 4s values is: " + str(total))

#column 5
column_five = my_array[:,4]
print(column_five)

total = 0
for i in range (0,column_five.size):
  total += column_five[i]

print("The sum of column 5's values is: " + str(total))

#column 6
column_six = my_array[:,0]
print(column_six)

total = 0
for i in range (0,column_six.size):
  total += column_six[i]

print("The sum of column 6's values is: " + str(total))


[[12 14 16 18 20 22]
 [ 5 10 15 20 25 30]
 [ 5  7  9 11 13 15]]
[12  5  5]
The sum of column 1's values is: 22
[14 10  7]
The sum of column 2's values is: 31
[16 15  9]
The sum of column 3's values is: 40
[18 20 11]
The sum of column 4s values is: 49
[20 25 13]
The sum of column 5's values is: 58
[12  5  5]
The sum of column 6's values is: 22


In [4]:
# Now format a SINGLE command that displays the first and second lines of the ndarray you just made
print(my_array[:2])

[[12 14 16 18 20 22]
 [ 5 10 15 20 25 30]]


In [13]:
# Format a command that slices the ndarray, giving only the first 3 columns of the first 2 rows.
# Display those values back in your code.
print(my_array[:2,[0,1,2]])

[[12 14 16]
 [ 5 10 15]]


In [14]:
# Finally, using the ndarray object you created above, use the .T method with it.
# For example, if your ndarray was named "myarray" then issue this command:
#
#  myarray.T
#
# What does that command do to the ndarray? Write your answer in the text block below.

my_array.T

array([[12,  5,  5],
       [14, 10,  7],
       [16, 15,  9],
       [18, 20, 11],
       [20, 25, 13],
       [22, 30, 15]])

Answer here.

**The .T method performs the transposition of this ndarray, switching the rows into columns and columns into rows**

# 2. Pandas

In class we created a DataFrame using the `read_csv` method. Another way to create a df is by hand, using Python lists. Below shows you how to do that, using a list of columns, a list of indexes, and a list of actual data for each record.

```python
df = pd.DataFrame(
    columns=['x','y','z'],
    index=['row1','row2','row3'],
    data=[[9,3,7],[1,2,4],[4,6,8]])
```

In [16]:
# Set up pandas and create the dataframe above. Then continue to work with the dataframe in the questions below.
import pandas as pd

df = pd.DataFrame(
    columns=['x','y','z'],
    index=['row1','row2','row3'],
    data=[[9,3,7],[1,2,4],[4,6,8]])

df

x  y  z
row1  9  3  7
row2  1  2  4
row3  4  6  8

In [17]:
# Format a command that displays the entire DataFrame.
print(df)

      x  y  z
row1  9  3  7
row2  1  2  4
row3  4  6  8


In [24]:
# Format a command that selects and returns only the SECOND row of data from the df.
df.loc["row2"]

x    1
y    2
z    4
Name: row2, dtype: int64

In [25]:
# Format a command that selects and returns only the `y` column of data from the df.
df.y

row1    3
row2    2
row3    6
Name: y, dtype: int64

In [26]:
# Format a command that displays the data types present in this DataFrame.
df.dtypes

x    int64
y    int64
z    int64
dtype: object

In [28]:
# Finally, using the DataFrame object you created above, use the .T method with it.
# For example, if your df was named "mydf" then issue this command:
#
#  mydf.T
#
# What does that command do to the DataFrame? Write your answer in the text block below.

df.T

row1  row2  row3
x     9     1     4
y     3     2     6
z     7     4     8

**The .T method performs the transposition of this dataframe, switching the rows into columns and columns into rows.**